services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    env_file: ".env"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres